import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { Amplify, ResourcesConfig } from 'aws-amplify'
import App from './App'
import './index.css'
import amplifyOutputs from '../amplify_outputs.json'

// Configure Amplify with outputs
// The amplify_outputs.json is generated by `npm run sandbox` or CI/CD
// A stub file is included for local development without backend
try {
  // Only configure if we have actual auth/data configuration
  if (amplifyOutputs && Object.keys(amplifyOutputs).length > 1) {
    Amplify.configure(amplifyOutputs as ResourcesConfig)
    console.log('Amplify configured successfully')
  } else {
    console.log('Amplify running in demo mode (no backend configured)')
  }
} catch (error) {
  console.log('Amplify configuration skipped:', error)
}

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
